# Generated by Django 4.1.7 on 2023-03-30 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_category_options_alter_contacts_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='original_price',
        ),
    ]
