# Generated by Django 4.1.7 on 2023-04-13 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_status_alter_product_trending'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Заказанный товар', 'verbose_name_plural': 'Заказанный товары'},
        ),
    ]
